# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    update_android_strings(
        xml_path: "app/src/main/res/values/strings.xml",
        block: lambda { |strings|
    			 # value must be a string, you can update what you want here.
                 strings['app_name'] = "Beta Demo Application"
               }
      )


    gradle(task: "clean assembleRelease",

            properties: {
               "android.injected.signing.store.file" => "examplestore",
               "android.injected.signing.store.password" => "linuxadmin",
               "android.injected.signing.key.alias" => "signFiles",
               "android.injected.signing.key.password" => "linuxadmin",
               "ApplicationId": "com.anko.demoapp.beta",
               "versionName": "2.0",
               "buildNumber": "10"
      }
    )

     appcenter_upload(
              api_token: "73af3f6df0612ed1cc2774edce1656671d38b5b9",
              owner_name: "mihailvoronkov",
              owner_type: "user", # Default is user - set to organization for appcenter organizations
              app_name: "demo-application1",
              file: "app/build/outputs/apk/release/app-release.apk",
              notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
            )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  lane :beta_max do
    update_android_strings(
        xml_path: "app/src/main/res/values/strings.xml",
        block: lambda { |strings|
    			 # value must be a string, you can update what you want here.
                 strings['app_name'] = "Beta Demo Application"
               }
      )
    gradle(task: "clean assembleRelease",

            properties: {
               "android.injected.signing.store.file" => "examplestore",
               "android.injected.signing.store.password" => "linuxadmin",
               "android.injected.signing.key.alias" => "signFiles",
               "android.injected.signing.key.password" => "linuxadmin",
               "ApplicationId": "com.anko.demoapp.beta",
               "versionName": ENV["VERSION"],
               "buildNumber": ENV["BUILD_NUMBER"]
      }
    )

     appcenter_upload(
              api_token: "73af3f6df0612ed1cc2774edce1656671d38b5b9",
              owner_name: "mihailvoronkov",
              owner_type: "user", # Default is user - set to organization for appcenter organizations
              app_name: "demo-application1",
              file: "app/build/outputs/apk/release/app-release.apk",
              notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
            )
  end 
  
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
